/*
 * Annie Lee
 * Sept 23 2021
 * Purpose: To understand how objects and classes work
 */

public class Dog {
    
    /*
     * There are 3 COMPONENTS to every OOP class
     *
     * 1) Instance variables (fields): represents the data each object keeps track of (attributes of the class)
     *         -can be primitive or non-primitive
     *         
     * 2) Constructor(s)
     *         -special method that INITIALIZES instance vars
     *         -must match name of class & have no return type
     *         public name of class (parameters) {}
         
     * 3) Behavious Methods
     *         -verb name
     *         -for doing an action with object
     *         - ex: bark(), run(), pee()
     */
    
    // INSTANCE variables (initialize)
    // So whenever we create new Dog object, dog obj will have the following instance vars
    String name;
    String noise;
    int age;
    
    // DEFAULT CONSTRUCTOR w/o parameters
    // auto generated by java if you don't add 
    // TO DEFINE INSTANCE VARS
    public Dog() {
        this.name = "Dawg";
        this.noise = "Woof";
        this.age = 0; // newborn puppy :3
    }
    
    // Overloading constructor (making more than one constructor)
    // Same name, must have different parameters
    public Dog(String name, String noise, int age) {
        this.name = name;
        this.noise = noise;
        this.age = age;
    }
    
    
    public void bark() {
        System.out.println(noise);
    }
    
    
    
}